# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Handoff < Formula
  desc "Cross-agent session handoff for AI coding tools (Claude Code, Cursor)."
  homepage "https://github.com/rosehgal/handoff"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rosehgal/handoff/releases/download/v0.1.0/handoff_darwin_amd64.tar.gz"
      sha256 "1d30a9fd31739484e73da0a8ad062e4bb5018170ce75fab2cb2530305a562ba2"

      define_method(:install) do
        bin.install "handoff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rosehgal/handoff/releases/download/v0.1.0/handoff_darwin_arm64.tar.gz"
      sha256 "553872e4adeeb0deac7f6cf4cdfd1c8e4911c2af58c465ff387db45b78b76a77"

      define_method(:install) do
        bin.install "handoff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rosehgal/handoff/releases/download/v0.1.0/handoff_linux_amd64.tar.gz"
      sha256 "077ecc80fb0eb415d35e8b0e68d0aa080a42c47f34e043c4a73f9034be27f0af"
      define_method(:install) do
        bin.install "handoff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rosehgal/handoff/releases/download/v0.1.0/handoff_linux_arm64.tar.gz"
      sha256 "e909ee7d8e83696c48251124121349053c2adcca20f605f1bff0c6b2496b9101"
      define_method(:install) do
        bin.install "handoff"
      end
    end
  end

  def caveats
    <<~EOS
      Wire handoff into your AI agents:
        handoff install      # Claude Code + Cursor
        handoff doctor       # verify
    EOS
  end

  test do
    assert_match "handoff", shell_output("#{bin}/handoff version")
  end
end
